ALTER TABLE "contract_items" ALTER COLUMN "unit_price" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "contracts" ALTER COLUMN "total_amount" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "product_dimensions" ALTER COLUMN "length" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "product_dimensions" ALTER COLUMN "depth" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "product_dimensions" ALTER COLUMN "diameter" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "product_dimensions" ALTER COLUMN "height" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "product_standard_boms" ALTER COLUMN "quantity_required" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "products" ALTER COLUMN "pricing_factor" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "manufactured_material_boms" ALTER COLUMN "quantity_required" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "material_unit_conversions" ALTER COLUMN "conversion_factor_to_base" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "materials" ALTER COLUMN "unit_price" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "materials" ALTER COLUMN "quantity" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "materials" ALTER COLUMN "opening_unit_price" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "materials" ALTER COLUMN "opening_quantity" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "materials" ALTER COLUMN "minimum_stock" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "offer_items" ALTER COLUMN "unit_price" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "offers" ALTER COLUMN "total_amount" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "inventory_transaction_items" ALTER COLUMN "quantity" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "inventory_transaction_items" ALTER COLUMN "unit_price" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "material_purchase_order_item_contract_items" ALTER COLUMN "quantity_allocated" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "material_purchase_order_items" ALTER COLUMN "quantity_ordered" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "material_purchase_order_items" ALTER COLUMN "unit_price" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "material_purchase_orders" ALTER COLUMN "total_amount" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "material_purchase_receipt_items" ALTER COLUMN "quantity_received" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "material_purchase_receipt_items" ALTER COLUMN "quantity_rejected" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "product_purchase_order_items" ALTER COLUMN "unit_price" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "product_purchase_orders" ALTER COLUMN "total_amount" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "outsourcing_order_items" ALTER COLUMN "quantity_ordered" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "outsourcing_order_items" ALTER COLUMN "unit_manufacturing_cost" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "outsourcing_orders" ALTER COLUMN "total_amount" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "outsourcing_receipt_items" ALTER COLUMN "quantity_received" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "outsourcing_receipt_items" ALTER COLUMN "quantity_rejected" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "maintenance_order_materials" ALTER COLUMN "quantity" SET DATA TYPE numeric(17, 5);--> statement-breakpoint
ALTER TABLE "maintenance_order_materials" ALTER COLUMN "unit_price" SET DATA TYPE numeric(17, 5);