ALTER TABLE "material_purchase_requisitions" RENAME COLUMN "purchasing_manager_decision" TO "inventory_control_decision";--> statement-breakpoint
ALTER TABLE "material_purchase_requisitions" RENAME COLUMN "purchasing_manager_decided_at" TO "inventory_control_decided_at";--> statement-breakpoint
ALTER TABLE "material_purchase_requisitions" RENAME COLUMN "purchasing_manager_decided_by" TO "inventory_control_decided_by";--> statement-breakpoint
ALTER TABLE "material_purchase_requisitions" RENAME COLUMN "purchasing_manager_decision_reason" TO "inventory_control_decision_reason";--> statement-breakpoint
ALTER TABLE "material_purchase_requisitions" DROP CONSTRAINT "mprq_purchasing_manager_pending_pair";--> statement-breakpoint
ALTER TABLE "material_purchase_requisitions" DROP CONSTRAINT "mprq_purchasing_manager_decision_reason_required";--> statement-breakpoint
ALTER TABLE "material_purchase_requisitions" DROP CONSTRAINT "mprq_purchasing_manager_decided_by_fk";
--> statement-breakpoint
ALTER TABLE "permissions" ALTER COLUMN "permission" SET DATA TYPE text;--> statement-breakpoint
DROP TYPE "public"."permission";--> statement-breakpoint
CREATE TYPE "public"."permission" AS ENUM('add_user', 'read_users', 'lookup_users', 'update_user', 'delete_user', 'add_role', 'read_roles', 'update_role', 'delete_role', 'add_department', 'read_departments', 'update_department', 'add_supplier', 'read_suppliers', 'update_supplier', 'print_suppliers_list', 'print_supplier_quotation_request', 'add_customer', 'read_customers', 'update_customer', 'add_material', 'read_materials', 'update_material', 'set_material_market_price', 'print_materials_list', 'use_unit_conversion_tool', 'add_manufactured_material_bom', 'read_manufactured_material_boms', 'update_manufactured_material_bom', 'read_material_reports', 'read_material_purchasing_reports', 'add_product', 'read_products', 'update_product', 'print_products_list', 'add_product_bom', 'read_product_boms', 'update_product_bom', 'read_inventory_transactions', 'read_material_purchase_orders', 'read_supplier_invoices', 'add_material_purchase_requisition', 'read_material_purchase_requisitions', 'update_material_purchase_requisition', 'approve_material_purchase_requisition_planning', 'approve_material_purchase_requisition_inventory_control', 'approve_material_purchase_requisition_manager', 'add_legacy_issue_permit', 'read_legacy_issue_permits', 'update_legacy_issue_permit');--> statement-breakpoint
ALTER TABLE "permissions" ALTER COLUMN "permission" SET DATA TYPE "public"."permission" USING "permission"::"public"."permission";--> statement-breakpoint
DROP INDEX "mprq_purchasing_manager_decision_idx";--> statement-breakpoint
DROP INDEX "mprq_purchasing_manager_decided_at_idx";--> statement-breakpoint
DROP INDEX "mprq_purchasing_manager_decided_by_idx";--> statement-breakpoint
ALTER TABLE "material_purchase_requisitions" ADD CONSTRAINT "mprq_inventory_control_decided_by_fk" FOREIGN KEY ("inventory_control_decided_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "mprq_inventory_control_decision_idx" ON "material_purchase_requisitions" USING btree ("inventory_control_decision");--> statement-breakpoint
CREATE INDEX "mprq_inventory_control_decided_at_idx" ON "material_purchase_requisitions" USING btree ("inventory_control_decided_at");--> statement-breakpoint
CREATE INDEX "mprq_inventory_control_decided_by_idx" ON "material_purchase_requisitions" USING btree ("inventory_control_decided_by");--> statement-breakpoint
ALTER TABLE "material_purchase_requisitions" ADD CONSTRAINT "mprq_inventory_control_pending_pair" CHECK (("material_purchase_requisitions"."inventory_control_decision" = 'pending') = ("material_purchase_requisitions"."inventory_control_decided_at" IS NULL) AND ("material_purchase_requisitions"."inventory_control_decision" = 'pending') = ("material_purchase_requisitions"."inventory_control_decided_by" IS NULL));--> statement-breakpoint
ALTER TABLE "material_purchase_requisitions" ADD CONSTRAINT "mprq_inventory_control_decision_reason_required" CHECK (("material_purchase_requisitions"."inventory_control_decision" = 'rejected') = ("material_purchase_requisitions"."inventory_control_decision_reason" IS NOT NULL));