import { Injectable, Inject, BadRequestException, UnauthorizedException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { JwtService } from '@nestjs/jwt';
import { Response } from 'express';
import bcrypt from 'bcryptjs';
import { eq, or, and, isNull, sql } from 'drizzle-orm';
import { users } from 'src/database/schema';
import { DRIZZLE, type DrizzleDB } from 'src/database/database.constants';
import { JwtPayload, User, UserWithRoleWithPermissions } from 'src/utils/types';
import { REFRESH_TOKEN_COOKIE } from 'src/utils/constants';
import { isProductionMode } from 'src/utils/env';
import { translate } from 'src/utils/i18n/translate';
import { RegisterDto } from './dto/register.dto';
import { LoginDto } from './dto/login.dto';

type SanitizedUser = Omit<User, 'password'>;
type SanitizedUserWithRoleWithPermissions = Omit<UserWithRoleWithPermissions, 'password'>;

type AuthenticationResponse = {
  message: string;
  accessToken: string;
  user: SanitizedUserWithRoleWithPermissions;
};

@Injectable()
export class AuthService {
  constructor(
    @Inject(DRIZZLE) private db: DrizzleDB,
    private config: ConfigService,
    private jwtService: JwtService,
  ) {}

  public async register(dto: RegisterDto, res: Response): Promise<AuthenticationResponse> {
    // Step 1: Ensure at least one identifier is provided
    if (!dto.email && !dto.phone)
      throw new BadRequestException(
        translate('Either email or phone must be provided.', 'يجب إدخال البريد الإلكتروني أو رقم الهاتف.'),
      );

    // Step 2: Hash password
    const hashedPassword = await bcrypt.hash(dto.password, 12);

    // Step 3: Insert new user (code is auto-generated by the DB trigger)
    const [newUser] = await this.db
      .insert(users)
      .values({
        code: sql`DEFAULT`,
        name: dto.name,
        email: dto.email,
        phone: dto.phone,
        password: hashedPassword,
        roleId: dto.roleId,
      })
      .returning();

    // Step 4: Generate tokens and set refresh token cookie
    const tokens = this.generateTokens(newUser.id);
    this.setRefreshTokenCookie(res, tokens.refreshToken);

    // Step 5: Fetch the newly registered user with their role & permissions
    const sanitizedUser = await this.getSanitizedUserWithRoleWithPermissions(newUser.id);

    return {
      message: 'Registration successful',
      accessToken: tokens.accessToken,
      user: sanitizedUser,
    };
  }

  public async login(dto: LoginDto, res: Response): Promise<AuthenticationResponse> {
    // Step 1: Ensure at least one identifier is provided
    if (!dto.email && !dto.phone)
      throw new BadRequestException(
        translate('Either email or phone must be provided.', 'يجب إدخال البريد الإلكتروني أو رقم الهاتف.'),
      );

    // Step 2: Find user by email or phone
    const user = await this.db.query.users.findFirst({
      where: and(
        or(dto.email ? eq(users.email, dto.email) : undefined, dto.phone ? eq(users.phone, dto.phone) : undefined),
        isNull(users.deletedAt),
      ),
    });

    if (!user) throw new UnauthorizedException(translate('Invalid credentials.', 'بيانات الاعتماد غير صحيحة.'));

    // Step 3: Verify password
    const isPasswordValid = await bcrypt.compare(dto.password, user.password);
    if (!isPasswordValid)
      throw new UnauthorizedException(translate('Invalid credentials.', 'بيانات الاعتماد غير صحيحة.'));

    // Step 4: Generate tokens and set refresh token cookie
    const tokens = this.generateTokens(user.id);
    this.setRefreshTokenCookie(res, tokens.refreshToken);

    // Step 5: Fetch user with role and permissions for the response
    const sanitizedUser = await this.getSanitizedUserWithRoleWithPermissions(user.id);

    return {
      message: 'Login successful',
      accessToken: tokens.accessToken,
      user: sanitizedUser,
    };
  }

  public async refreshAccessToken(userId: string): Promise<AuthenticationResponse> {
    const tokens = this.generateTokens(userId);
    const user = await this.getSanitizedUserWithRoleWithPermissions(userId);
    return {
      message: 'New access token generated',
      accessToken: tokens.accessToken,
      user,
    };
  }

  public logout(res: Response) {
    this.removeRefreshTokenCookie(res);
    return { message: 'Logout successful' };
  }

  public async getUser(id: string) {
    const [user] = await this.db
      .select()
      .from(users)
      .where(and(eq(users.id, id), isNull(users.deletedAt)));
    if (!user)
      throw new UnauthorizedException(
        translate('Access denied: User does not exist.', 'تم رفض الوصول: المستخدم غير موجود.'),
      );
    return user;
  }

  public sanitizeUser(user: User): SanitizedUser {
    const { password, ...sanitizedUser } = user; // Remove sensitive fields before sending to client
    void password; // marks it as intentionally unused
    return sanitizedUser;
  }

  /** Fetches the user along with their role and the role's permissions. Used by `PermissionGuard`. */
  public async getSanitizedUserWithRoleWithPermissions(id: string): Promise<SanitizedUserWithRoleWithPermissions> {
    const rawUser = await this.db.query.users.findFirst({
      where: and(eq(users.id, id), isNull(users.deletedAt)),
      with: { role: { with: { permissions: true } } },
    });

    if (!rawUser)
      throw new UnauthorizedException(
        translate('Access denied: User does not exist.', 'تم رفض الوصول: المستخدم غير موجود.'),
      );

    // Flatten the permissions list
    const user = rawUser.role
      ? { ...rawUser, role: { ...rawUser.role, permissions: rawUser.role.permissions.map((p) => p.permission) } }
      : rawUser;

    // Sanitize User object
    const { password, ...sanitizedUser } = user; // Remove sensitive fields before sending to client
    void password; // marks it as intentionally unused
    return sanitizedUser as SanitizedUserWithRoleWithPermissions;
  }

  // ==================== TOKEN UTILITIES ====================

  private generateTokens(userId: string) {
    const accessPayload: JwtPayload = { id: userId, type: 'access' };
    const refreshPayload: JwtPayload = { id: userId, type: 'refresh' };

    const accessToken = this.jwtService.sign(
      { ...accessPayload },
      {
        secret: this.config.getOrThrow<string>('AT_SECRET_KEY'),
        expiresIn: `${this.config.getOrThrow<number>('AT_EXPIRATION_TIME')}s`,
      },
    );

    const refreshToken = this.jwtService.sign(
      { ...refreshPayload },
      {
        secret: this.config.getOrThrow<string>('RT_SECRET_KEY'),
        expiresIn: `${this.config.getOrThrow<number>('RT_EXPIRATION_TIME')}s`,
      },
    );

    return { accessToken, refreshToken };
  }

  private setRefreshTokenCookie(res: Response, refreshToken: string) {
    res.cookie(REFRESH_TOKEN_COOKIE, refreshToken, {
      path: '/', // Cookie available for all routes
      httpOnly: true, // Prevents JavaScript access (XSS protection)
      secure: isProductionMode(), // HTTPS only in production
      sameSite: 'lax' as const, // CSRF protection while allowing navigation
      maxAge: this.config.getOrThrow<number>('RT_EXPIRATION_TIME') * 1000, // Convert seconds to milliseconds
    });
  }

  private removeRefreshTokenCookie(res: Response) {
    res.clearCookie(REFRESH_TOKEN_COOKIE, { path: '/' });
  }
}
